Homebrew/formulae.brew.sh

_includes/formulae.html
_layouts/formula.html
_layouts/formula_json.json

Use more of the metadata provided in the JSON output (including new stuff from https://github.com/Homebrew/brew/pull/4160) and improve the ordering to better match a formula file.
Fixes #8.
Fixes #9.
Fixes #11.

Add and use more metadata

---

_config.yml

This has been updated now we have a newer version of jekyll-remote-theme.

_config.yml: use brew.sh theme name.

---

_config.yml

Will kick in after https://github.com/Homebrew/brew.sh/pull/222 lands

set custom link

---

.travis.yml
Rakefile

This is done/tested by the homebrew-core job for now.

Don't try to generate analytics on CI run.

---

_layouts/formula_json.json

These need to use `full_name` otherwise always are `0`.
Fixes https://github.com/Homebrew/brew/issues/5147

formula_json: fix versioned formula analytics.

---

script/generate.rb

script/generate: remove deleted formulae.

---

Gemfile.lock

Gemfile.lock: use latest bundler.

---

script/generate.rb

#13 
Add json generation to `generate.rb` for casks.
This does **not** generate analytics or HTML as this will be addressed in a separate PR.

Update generate.rb to create json files for casks in new directories for API

---

Rakefile

per https://github.com/Homebrew/formulae.brew.sh/pull/92#issuecomment-457602159

add cask-install

---

_config.yml

Set up a search domain for docsearch. See https://github.com/Homebrew/brew.sh/pull/326

Add search domain config

---

_includes/formula.html

This doesn't really add anything except visual noise.

includes/formula: remove formula table tick.

---

.gitignore
README.md
_layouts/analytics.html
_layouts/analytics_json.json
_layouts/formula.html
api/formula.json
docs/api.md
formula_index.html
script/generate-cask.rb
script/generate.rb

Non-Cask-related fixes cherry-picked from #114.

various markup and script fixes

---

_includes/formulae.html
_layouts/analytics.html
_layouts/formula.html
_layouts/formula_json.json

… and update one file missed in #126.

use double quotes around strings in liquid tags

---

_layouts/cask.html

fix for missing related formulae in cask output

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml

Try to avoid issues (we've had a few) where people have an issue with the generated contents rather than the actual site or logic.

Add issue templates

---

.github/workflows/scheduled.yml
_layouts/formula.html

[As suggested](https://github.com/Homebrew/homebrew-core/pull/53939#issuecomment-620959807), assume the task of periodically regenerating site data from changes in homebrew-core, homebrew-cask, and linuxbrew-core. Will need `secrets.ANALYTICS_JSON_KEY` and `secrets.ANALYTICS_JSON_KEY_B64` added to this repo for analytics processing to work.

actions: periodically generate site data

---

.github/workflows/scheduled.yml
Rakefile
_layouts/analytics_json.json
_layouts/cask.html
_layouts/cask_json.json
_layouts/formula.html
analytics/index.html
api/analytics/cask-install/homebrew-cask/30d.json
api/analytics/cask-install/homebrew-cask/365d.json
api/analytics/cask-install/homebrew-cask/90d.json

Adds install stats to cask pages, JSON, and the analytics summary page.

Display install statistics for individual casks

---

Rakefile

`<<` adds the entire array to the left operand, while `+=` adds each item individually.

Use correct operator for array combination

---

docs/api.md

Update the API doc page to mention Linux, casks, and display the page title.

Update API docs

---

.editorconfig
_api_formula_linux.json.in
_includes/cask.html
_includes/casks.html
_includes/formula.html
_includes/formulae.html
_layouts/analytics.html
_layouts/analytics_json.json
_layouts/cask.html
_layouts/cask_json.json
_layouts/formula.html
_layouts/formula_json.json
analytics-linux/index.html
analytics/index.md
api/cask.json
api/formula-linux.json
api/formula.json
api/index.html
cask_index.html
docs/api.md
formula_index.html
formula_linux_index.html

Various fixes that make the site source easier to understand and edit.

Clean up generated markup

---

_layouts/formula.html

Use licensing data now provided by Homebrew/brew and some formulae.

formula: add license.

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

- only attempted scheduled job on `push` (where secrets are around)
- use more Homebrew actions
- fix `pull_request: []` warning
- use `@main` actions

GitHub Actions cleanup

---

_includes/install_command.html

Fix spacing

---

_layouts/formula.html

Account for any required architecture, and capitalize the names of other requirements. 
Requires Homebrew/brew#9021.

Improve display of requirements

---

_includes/install_command.html
_layouts/cask.html
_layouts/formula.html
analytics-linux/build-error/30d/index.html
analytics-linux/build-error/index.html
analytics-linux/index.html
analytics-linux/install-on-request/30d/index.html
analytics-linux/install-on-request/index.html
analytics-linux/install/30d/index.html
analytics-linux/install/index.html
analytics/build-error/30d/index.html
analytics/build-error/index.html
analytics/cask-install/30d/index.html
analytics/cask-install/index.html
analytics/index.md
analytics/install-on-request/30d/index.html
analytics/install-on-request/index.html
analytics/install/30d/index.html
analytics/install/index.html
analytics/os-version/30d/index.html
analytics/os-version/index.html
api/index.html
docs/api.md

Updating to reflect changes in Homebrew/brew#9247. I also reduced the file count by using `redirect_from` for redirects.

Update suggested command for casks

---

.github/workflows/scheduled.yml
Rakefile

Reverts Homebrew/formulae.brew.sh#421

Revert "Rakefile: temporarily disable Linux analytics."

---

_layouts/formula.html
docs/api.md

Update example API output to match current output. Also, update the bottle table formatting slightly to add a separator, de-bold the OS names and add spacing to the HTML output.

Update API docs and bottle table

---

.github/workflows/scheduled.yml

Moving this to be a repository-scoped token with a different name.
While we're here, let my editor's auto formatted cleanup the YAML.

scheduled: update token name.

---

_layouts/cask.html
_layouts/formula.html

Add classes to `<p>` tags to aid future search improvements.

Add classes to formula/cask info

---

_layouts/formula.html

Hello there, this is a pretty naive patch providing direct links to conflicts on formulae pages. Bye :wave:

_layouts/formula.html: provide link to conflicting formulae

---

.github/workflows/scheduled.yml

Follow-up to #482
I changed the files to be checked and committed by `git` to include the new `_data/bottle{,-linux}` and `api/bottle{,-linux}` directories but forgot to add them to `git` using `git add`.

Fix bottle API files

---

_layouts/formula.html

Wasn't able to test this locally because it does not want to build.

formulae: add a disable time and reason to the title

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml

Set `concurrency` on all workflows where it makes sense to do so.

.github/workflows: add more `concurrency`.

---

.github/workflows/scheduled.yml

This should fix the stalled CI

CI: set content write permission

---

.github/workflows/scheduled.yml

Part 2 of the conversion to GitHub actions deploys to pages

feature: stop commiting generated files

---

.github/workflows/scheduled.yml

Currently the generating is too slow to complete before the new run

fix: split CI components into multiple jobs

---

.github/workflows/scheduled.yml

ci: clean before build

---

.github/workflows/scheduled.yml

scheduled: use existing algolia crawler

---

.github/workflows/scheduled.yml
Rakefile
_includes/api-samples/analytics_cask_install_homebrew_cask_30d.md
_includes/api-samples/analytics_install_30d.md
_includes/api-samples/analytics_install_homebrew_core_30d.md
_includes/api-samples/bottle_wget.md
_includes/api-samples/cask_docker.md
_includes/api-samples/cask_source_vagrant.md
_includes/api-samples/formula.md
_includes/api-samples/formula_wget.md
_includes/api-samples/versions_casks.md
_includes/api-samples/versions_formulae.md

We were not uploading analytics API or Linux analytics pages.
Also, temporarily disable sample generation until it's working.

Deploy more analytics data

---

_layouts/cask.html
_layouts/formula.html

This will make the source link to the same revision as the page was generated from.

layouts: use tap_revision fields.

---

_data/analytics/cask-install/homebrew-cask/30d.json
_data/analytics/install/homebrew-core/30d.json
api/analytics/cask-install/homebrew-cask/30d.json
api/analytics/install/homebrew-core/30d.json
api/versions-casks.json
api/versions-formulae.json

These are `curl`d so need to be present before they can be properly regenerated.

Fix samples by adding more missing files

---

Rakefile

Rakefile: don't generate API data from API data

---

Rakefile

The category wasn't quite correct for these.

Rakefile: fix core tap analytics API generation

---

script/generate-api-samples.rb

Let's ensure that we blow up if we don't get what we need.

script/generate-api-samples: abort on failures.

---

.github/workflows/scheduled.yml
script/generate-api-samples.rb

Actually fail if this detects problems.

workflows/scheduled: validate build.

---

.gitignore

These files are also generated for the site, so lets ignore them in git so I can keep them around locally.

Add more generated files to `.gitignore`

---

script/generate-cask.rb

See https://github.com/Homebrew/brew/pull/14615
This will set placeholder values in the generated hash.

generate-cask: enable `Cask.generating_hash!` mode

---

.github/workflows/scheduled.yml

This sometimes fails so let's retry it.

workflows/scheduled: retry analytics query.

---

.github/workflows/scheduled.yml

This stops the scripts outputting about `brew developer`.

workflows/scheduled: set HOMEBREW_DEVELOPER.

---

.github/workflows/scheduled.yml
Rakefile
script/generate-api-samples.rb

This should run fine without `brew ruby`.

Rakefile: remove final "brew ruby" usage.

---

.github/workflows/scheduled.yml

Needed with new flow.
CC @SMillerDev

scheduled.yml: set HOMEBREW_INFLUXDB_TOKEN.

---

_layouts/formula.html
_layouts/formula_json.json

This variable no longer exists.

layouts/formula*: use correct analytics source path.

---

.github/workflows/scheduled.yml

after setup-homebrew changes
Fixes #921.

workflows/scheduled: fix taps not being updated

---

.github/workflows/scheduled.yml

This reverts commit 9d0fd54712ac51d076711887c331eb276deadf18.

Revert "workflows/schduled: temporarily use previous analytics data"

---

.github/workflows/scheduled.yml

[MORE REVERTS FOR THE REVERT GOD](https://wh40k.lexicanum.com/wiki/Blood_for_the_Blood_God)
Reverts Homebrew/formulae.brew.sh#944

Revert "Revert "Revert "workflows/scheduled: temporarily use previous analytics data"""

---

.github/workflows/scheduled.yml
.github/workflows/tests.yml
.gitignore
Rakefile

- Don't need `ANALYTICS_JSON_KEY` any more
- Try to also generate API samples and, for non-forks, analytics
- Try to also build and validate Jekyll site

Improve analytics generation testing

---

_layouts/formula.html

It's more widely used now.
Fixes #963

layouts/formula: place Apple Silicon above Intel.

---

.github/workflows/scheduled.yml

These need to both be updated at once.

workflows/scheduled: use download/upload-artifact v4.

---

.github/workflows/scheduled.yml

Reverts Homebrew/formulae.brew.sh#1004
Again, needs https://github.com/actions/download-artifact/issues/249 resolved first

Revert "build(deps): bump actions/upload-pages-artifact from 2 to 3"

---

_layouts/cask.html

See https://github.com/Homebrew/formulae.brew.sh/pull/1008#discussion_r1434297489

layouts/cask: fix cask variations size.

---

.github/workflows/scheduled.yml

revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert revert 
We're back
Reverts Homebrew/formulae.brew.sh#1105

Revert "Revert "Revert "Revert "Revert "workflows/scheduled: temporarily use previous analytics data"""""

---

.github/dependabot.yml
.github/workflows/scheduled.yml
.github/workflows/tests.yml

This should hopefully be sufficiently stable now.

workflows: use artifact v4

---

_config.yml

As in https://github.com/Homebrew/brew.sh/pull/931

Use SVG logo in header

---

_includes/cask.html
_includes/formula.html
_includes/install_command.html
_layouts/analytics.html
_layouts/cask.html
_layouts/formula.html

Make sure we handle input consistently

layouts: consistent data handling

---

analytics/brew-command-run/30d/index.html
analytics/brew-command-run/365d/index.html
analytics/brew-command-run/90d/index.html

This output the new data generated by Homebrew's analytics for commands run by users.

analytics: add brew-command-run pages.

---

_layouts/analytics.html
analytics/brew-command-run/30d/index.html
analytics/brew-command-run/365d/index.html
analytics/brew-command-run/90d/index.html
analytics/index.md

Improve various parts of the output and fix data display.

analytics: improve brew-command-run output.

---

_layouts/analytics.html
_layouts/cask_json.json

Follow-up to #1149 with more versioned cask fixes.

fixes for versioned casks' API and analytics

---

.gitignore
Rakefile

- `.gitignore`: add `api/internal/` and sort contents
- `Rakefile`: add paths in `CLOBBER.include` lines, plus minor fixes

update ignored paths

---

.github/workflows/tests.yml

Don't skip these jobs when the ref is `master`.

workflows/tests: fix master/scheduled CI.

---

_config.yml
cask-font_index.html
cask_index.html
docs/api.md
formula_index.html

Needed for documentation linting incoming in #1229.

Use `repository` instead of `repo`

---

Gemfile
Gemfile.lock

Extracted from https://github.com/Homebrew/formulae.brew.sh/pull/1243

Gemfile: add html-proofer and mdl.

---

.github/workflows/tests.yml

For [github.com/orgs/Homebrew/security/campaigns/1](https://github.com/orgs/Homebrew/security/campaigns/1).

workflows: fix artipacked zizmor findings

---

.github/workflows/tests.yml
Rakefile

This was migrated to Homebrew/brew.

tests: remove homebrew-formula-analytics
