Homebrew/formulae.brew.sh

_layouts/formula.html, _layouts/formula_json.json, api/formulae.json
Need to remove the `@` from the name to get the correct data file. Also, as a result, don't render the `@`-less name in `formulae.json` or the individual formula JSON files to avoid confusion.
Fixes #4.
=> Fix versioned formulae.

_layouts/formula.html
Don't need to remove the `@` or `.` from their names.
Also, ensure that a `0` is shown rather than empty row if there's been no build errors.
=> formula: fix versioned formulae analytics display.

.travis.yml, Gemfile, Gemfile.lock, Rakefile, _includes/formula.html, _includes/formulae.html, _layouts/formula.html, _layouts/formula_json.json
Run `html-proofer` and `jsonlint` on CI runs and fix the errors that cropped up from `html-proofer` locally.
=> Add more CI checks for HTML/JSON

Rakefile
- set `HOMEBREW_FORCE_HOMEBREW_ON_LINUX` to use the correct prefix/cellar for macOS.
- remove accidental exclusion of some homebrew-core analytics
- tweak Rakefile style
=> Rakefile: update generation logic.

formula_index.html
It's easier to put this in the root both to find it and to mean that `formula` can be deleted and recreated by `script/generate`.
Fixes #72.
=> formula_index: restore from formula/index.html.

_layouts/analytics.html, analytics/build-error/30d/index.html, analytics/build-error/365d/index.html, analytics/build-error/90d/index.html, analytics/cask-install/30d/index.html, analytics/cask-install/365d/index.html, analytics/cask-install/90d/index.html, analytics/index.html, analytics/install-on-request/30d/index.html, analytics/install-on-request/365d/index.html, analytics/install-on-request/90d/index.html, analytics/install/30d/index.html, analytics/install/365d/index.html, analytics/install/90d/index.html
Make clearer which are casks and which are formulae.
Additionally, don’t link to formulae on casks page.
CC @brianmorton
=> Improve Formula/Cask analytics differentiation

script/generate-cask.rb, script/generate.rb
Refactored both to increase readability and reduce disk access by reading each template only once. Also appends a line break to the formula data files, as is done for casks.
Runtime for `generate.rb` before & after: 
```
$ time rake formulae
brew ruby script/generate.rb
real	0m57.903s
user	0m25.730s
sys	0m30.266s
```
```
$ time rake formulae
brew ruby script/generate.rb
real	0m51.447s
user	0m23.568s
sys	0m26.660s
```
And for `generate-cask.rb`:
```
$ time rake cask
brew ruby script/generate-cask.rb
real	0m7.693s
user	0m3.500s
sys	0m3.226s
```
```
$ time rake cask
brew ruby script/generate-cask.rb
real	0m5.923s
user	0m3.172s
sys	0m2.655s
```
=> optimize file generation scripts

.github/workflows/tests.yml
These seem to be mainly failing and we're pushing almost entirely automatically so don't need to run CI.
=> GitHub Actions: don't build master.

Rakefile
e.g. caveats for 'cockroach' formula or 'adoptopenjdk' cask. Only seems to be an issue when building locally, though.
cc @MikeMcQuaid
=> Suppress control characters around text using Formatter

_layouts/cask.html, _layouts/formula.html
This places caveats for both formulae and casks within a table, giving it them slightly more distinctive background. It also attempts to more closely replicate how they appear on the command line. (The `capture` trick works around Liquid's inability to match newlines against `\n` in strings.)
=> Reformat and display caveats within table

.github/workflows/tests.yml
- The Actions UI showed a deprecation warning for `version`:
Input 'version' has been deprecated with message: The version property will not be supported after October 1, 2019. Use ruby-version instead
=> CI: Switch Actions 'version' parameter for 'ruby-version'

_layouts/formula.html
- This was hardcoded to the macOS formula data directory by mistake, causing everything to work fine _except_ Linux-only formulae which obviously aren't present in the macOS data files.
- The analytics part of this file was using the `formula_path` variable correctly, which meant that the data appeared fine, but the Linux-only formulae just didn't have names or anything that relied on a lookup based on name.
Before, `/formula-linux/adoptopenjdk`:
After:
=> Use the formula_path variable to get the OS-scoped formula name

_includes/formulae.html
- #195 was almost there but not quite!
- We need to use `formula_path` in two places: once to get the correct formula data, and once to specify the path for the formula.html includes - otherwise, as was happening here, it defaults to `formula`.
=> Really fix dependency list path for Linux formulae

Rakefile
- In https://github.com/Homebrew/homebrew-formula-analytics/pull/129, `brew formula-analytics` switched to use `CLI::Parser`. While doing so, `--json` and `--all-core-formulae-json` were set to be [conflicting](https://github.com/Homebrew/homebrew-formula-analytics/blob/master/cmd/formula-analytics.rb#L34).
- This caused an issue where the GitHub Action to generate the data for these formulae.brew.sh pages [couldn't run](https://github.com/Homebrew/homebrew-core/issues/49840) because it was using both of the arguments.
- Instead, make this only use `--all-core-formulae-json` as it's the more specific one.
Fixes https://github.com/Homebrew/homebrew-core/issues/49840.
=> The `--json` and `--all-core-formulae-json` flags are exclusive

Rakefile
- This is a follow up to #244 as I missed some cases!
- We only use `--all-core-formulae-json` for `core-build-error` etc.
categories. There are also normal `build-error` etc. categories that
need the plain `--json` flags.
- This adds `--json` to the build-error flags if the existing category
names don't have `--all-core-formulae-json` already specified. This
seemed tidier than adding extra `when`s to the `case` statement for
all the other categories.
=> Fix conflicting flags in formula-analytics calls for every combination

Rakefile
- Follow up to #244 and #245.
- The confusion between what needs `--` and what doesn't strikes again!
It doesn't help that `--#{category_flags}` confuses this even more.
=> Fix brew formula-analytics --json --build-error category flags again

_layouts/formula.html
For formulae that specify Requirements, use the additional data made available in Homebrew/brew#7105 to indicate specific version and context requirements; e.g. https://formulae.brew.sh/formula/needle will show that it needs different Xcode versions for being built vs. just being run.
=> Display additional requirements data

.github/workflows/tests.yml, Gemfile.lock, Rakefile
- Use Ruby 2.6
- Use Bundler 1.x (as comes with Ruby 2.6)
- Ignore more "not an error" HTTP status codes
=> CI cleanup

Rakefile, _config.yml, _layouts/cask.html, _layouts/formula.html, cask_index.html, docs/api.md, formula_index.html, formula_linux_index.html, script/generate-cask.rb, script/generate.rb
This PR is an attempt to make the tap configurable, such that forks may build the website for their own 3rd party taps.
This PR is comprised of two primary changes:
- Rakefile and generator scripts:
`script/generate.rb` and `script/generate-cask.rb` are modified to accept a tap argument of the form "owner/repo". If the argument is omitted or empty, they default to their present values (CoreTap and default_cask_tap, respectively). To pair with this change, the corresponding Rakefile tasks are also modified to accept a tap argument and to pass it along to the scripts.
- Tap info in Jekyll configuration
The second main change in this PR, is the addition of tap information to the Jekyll configuration. These configuration options are then used in the cask and formula templates when …
=> Make tap configurable

README.md, Rakefile
The primary purpose of this PR is to update the Rakefile such that the data generation tasks pull their default tap names from the jekyll configuration. The benefit of this is reducing the number of places where this information is duplicated (thereby simplifying the configuration changes necessary for tap-forks).
Additionally, this PR configures the rake CLOBBER listing such that the `rake clobber` task is capable of clearing out not only jekyll's generated site, but also the generated formula/cask/analytics data files. Rake differentiates clean and clobber where clobber is a more extensive or "thorough" cleaning. I think this makes a very good differentiating between cleaning the jekyll site (which is not committed) and clobbering the homebrew data (which _is_ committed). Clobber is a …
=> Rake updates

Rakefile
This allows the data generation tasks to be run outside the context of a
Bundler gem bundle. This is necessary for the core and cask taps to
trigger data re-generation from their Action workflows.
Hopefully this is a short-term solution, as it's preferable for rake to
be able to assume (and leverage) access to its bundled gems.
see https://github.com/Homebrew/formulae.brew.sh/pull/271#issuecomment-615897164
[Example invocation](https://github.com/jasonkarns/homebrew-core/runs/598148507?check_suite_focus=true) of rake from an external tap (my fork of homebrew-core, pointing at this PR's branch of formulae.brew.sh)
=> Allow use of rake without a gem bundle

.github/workflows/scheduled.yml, _data/analytics/cask-install/homebrew-cask/30d.json, _data/analytics/cask-install/homebrew-cask/365d.json, _data/analytics/cask-install/homebrew-cask/90d.json
And allow them to be generated by not setting `HOMEBREW_NO_ANALYTICS` globally.
=> Generate initial homebrew/cask analytics

.github/workflows/scheduled.yml
Fix for `HOMEBREW_PREFIX` not being defined if `brew` is pre-installed, as per Homebrew/brew#7555.
=> workflows/scheduled: fix for pre-installed Linuxbrew

_layouts/cask_json.json, _layouts/formula_json.json, cask_index.html, formula_index.html, formula_linux_index.html
Adds a [date](https://github.com/Homebrew/formulae.brew.sh/pull/277#issuecomment-623114612) to the bottom of formulae/casks lists ("Last updated at 2020-05-15 11:30") and JSON results (`generated_date: "2020-05-15"`).
=> Add generated_date to JSON & HTML pages

_layouts/cask.html
Properly handle multiple ranges: `macOS >= 10.11 and macOS <= 10.14` and multiple versions: `macOS == 10.11 / 10.12 / 10.13 / 10.14 / 10.15`.
=> Improve display of macOS requirements for casks

_layouts/cask.html, _layouts/formula.html
Original logic would skip showing the table if the formula hadn't had any installs in the last 30 days. This also increases the DRY factor by looping through each days interval.
=> Always show analytics table on formula/cask pages

_includes/formula.html, _layouts/cask.html, _layouts/formula.html
- sets a "disabled" or "deprecated" class and hovertext for titles of such formulae (relies on changes to site theme in https://github.com/Homebrew/brew.sh/pull/516) in both the formula page title and formula listings
- displays cask descriptions if they exist
- replaces the underscore with a space for formulae specifying `license :public_domain`
As suggested in https://github.com/Homebrew/brew/pull/8166.
=> Show additional formula/cask info

.github/workflows/scheduled.yml
We used to run this on every push so seems fair enough to run it a little more often.
=> workflows/scheduled: run every hour.

.gitignore, Rakefile
These are already in Git so it makes it harder and more error-prone than necessary to do a build. Also, `rake serve` does not depend on `rake build` to make this incremental for the user (because it's so slow to build).
While we're here, fix the `.gitignore` too.
=> Rakefile: don't require building formulae/casks/analytics.

script/generate-cask.rb
Fixes CI error:
```
brew ruby script/generate-cask.rb Homebrew/cask
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:62:in `load': missing keyword: config (ArgumentError)
from script/generate-cask.rb:15:in `block in <main>'
from script/generate-cask.rb:14:in `each'
from script/generate-cask.rb:14:in `<main>'
```
Closes https://github.com/Homebrew/brew/pull/8828.
=> Fix cask loading

script/generate-cask.rb
Use `Cask::CaskLoader::load` instead of creating a `Cask::CaskLoader::FromPathLoader` instance manually.
=> Simplify loading casks.

_includes/code_snippet.html, _includes/install_command.html, _layouts/cask.html, _layouts/formula.html
Adds install command user can directly copy and paste.
Fixes #329 
Points to finalise
=> Add install command and copy to clipboard

_includes/formulae.html, _layouts/cask.html, script/generate.rb
1. Add display of cask `arch:` requirements
- https://formulae.brew.sh/cask/locklizard-safeguard-viewer
2. For casks or formulae that specify formula dependencies using an alias or former name, look up the canonical name first
- https://formulae.brew.sh/cask/cellery
- https://formulae.brew.sh/cask/ibm-cloud-cli
- https://formulae.brew.sh/formula/dotnet
- https://formulae.brew.sh/formula/ncspot
=> Additional support for requirements

_layouts/cask.html, _layouts/formula.html
Makes it usable with branches that aren't called `master`
=> rename GitHub branches to HEAD

_layouts/formula.html
Fixes #407: splits macOS bottle support list into new table with separate rows for both architectures. Also removes reference to `devel`.
=> Split formula bottle support list into new table

_layouts/formula.html
Account for the cases where a homebrew-core formula [has no bottles](https://formulae.brew.sh/formula/alsa-lib) (usually b/c it requires Linux, but [not always](https://formulae.brew.sh/formula/clang-format@8)) or a linuxbrew-core formula [only lists macOS bottles](https://formulae.brew.sh/formula-linux/swift). Fixes #416.
=> Hide bottle table if none available

Rakefile
It's currently broken and blocking all updates:
https://github.com/Homebrew/formulae.brew.sh/runs/1903832906?check_suite_focus=true#step:9:69
CC https://github.com/Homebrew/formulae.brew.sh/pull/150 @issyl0 @sjackman who I think have access to the Linuxbrew analytics permissions. Ideally we'd get these transferred over to the Homebrew organisation so they can share credentials. We have a `From https://console.developers.google.com/apis/credentials?project=homebrew-analytics` note in 1Password for the Homebrew key but nothing similar for the Linuxbrew one.
=> Rakefile: temporarily disable Linux analytics.

_layouts/formula.html
Fixes https://github.com/Homebrew/formulae.brew.sh/issues/426.
Before:
After:
(no arm64)
(with arm64)
=> Split bottle list by architecture types.

_layouts/analytics.html, analytics-linux/build-error/30d/index.html, analytics-linux/build-error/365d/index.html, analytics-linux/build-error/90d/index.html, analytics-linux/install-on-request/30d/index.html, analytics-linux/install-on-request/365d/index.html, analytics-linux/install-on-request/90d/index.html, analytics-linux/install/30d/index.html, analytics-linux/install/365d/index.html, analytics-linux/install/90d/index.html, analytics/build-error/30d/index.html, analytics/build-error/365d/index.html, analytics/build-error/90d/index.html, analytics/cask-install/30d/index.html, analytics/cask-install/365d/index.html, analytics/cask-install/90d/index.html, analytics/install-on-request/30d/index.html, analytics/install-on-request/365d/index.html, analytics/install-on-request/90d/index.html, analytics/install/30d/index.html, analytics/install/365d/index.html, analytics/install/90d/index.html, analytics/os-version/30d/index.html, analytics/os-version/365d/index.html, analytics/os-version/90d/index.html
Change analytics page titles from "Formula Install Events" to "Formula Install Events (30 days)". This is to support https://github.com/algolia/docsearch-configs/pull/3945. That way, the days are identifiable from the title without needing to read farther (and look at the `h3` `/api` url)
Before:
After:
=> Add days to analytics page titles

_layouts/formula.html
Currently, `all` bottles aren't handled properly:
(Taken from https://formulae.brew.sh/formula/ack#default).
This PR is an attempt to improve handling for `all` bottles.
=> _layouts/formula.html: improve `all` bottle handling

.github/workflows/scheduled.yml, _api_bottle.json.in, _layouts/bottle_json.json, _layouts/formula.html, script/generate.rb
This PR adds the `/api/bottle` JSON API for formulae in homebrew/core. I've tested this locally on my mac but I haven't tested it out on a Linux machine.
This relies on https://github.com/Homebrew/brew/pull/11488 to be merged so it can use the new `Formula#to_recursive_bottle_hash` method to generate the bottle API files. This PR should not be merged until that brew PR has been merged.
=> Add `/api/bottle/$FORMULA.json`

docs/api.md
This PR updates sample API response in the API docs. It might include some changes in https://github.com/Homebrew/formulae.brew.sh/pull/486. Maybe we should get that merged before this PR gets merged.
Regarding the previous discussions about making a Homebrew mirror https://github.com/Homebrew/discussions/discussions/1906, this is our first step to make mirroring easier by stabilizing some fields in JSON API.
Mirror tools made by mirror maintainers from Linux user groups in China require specific fields from the JSON API for the mirroring tools to work. Specifically, they need the following structures:
* JSON API response should at least contains the following structure (or fields):
```
Response = [Formula*]
Formula = { name, Versions, Bottle, revision }
Bottle = BottleStable? …
```
=> docs: stabilize bottle API responses

.github/workflows/scheduled.yml, script/generate-cask.rb
This PR adds a new `/api/cask-source/foo.rb` API for getting the text contents of a cask file.
This will eventually be used to allow casks to be installed without needing `homebrew/cask` to be tapped.
=> Add cask sources API

.github/workflows/scheduled.yml, .github/workflows/tests.yml
- I saw this in the CI output:
```
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
```
=> tests: Use the maintained `ruby/setup-ruby` Action

script/generate-cask.rb, script/generate.rb
Now that we can create `variations` hashes for formulae and casks, let's include them here in the JSON API. For a little bit, the cask API did include the variations hash, but that was changed when we started only doing the `variations` calculations when `--variations` was passed to `brew info --json`. This PR re-adds this functionality and adds it for formulae.
=> Use `#to_hash_with_variations` to generate formula and cask JSON

.github/workflows/scheduled.yml
Use https://github.com/actions/upload-pages-artifact and https://github.com/actions/deploy-pages to deploy to GitHub pages every hour instead of the automagic option
=> CI: use github actions to release pages

_layouts/cask.html, _layouts/formula.html
`HEAD` gives a slightly weird experience on GitHub as it:
- Shows the current commit hash in some places (like the branch picker)
- Doesn't show the current branch
- Will just switch to using `HEAD`'s commit hash when using relative links (like click the name of the parent path)
- This means future links are connected to a specific commit unnecessarily instead of the branch
Using `-` instead avoids hardcoding the name of the default branch while making the behaviour nicer when actually on GitHub as it simply redirects to the default branch. This keeps the same behaviour as `HEAD` but avoids the disadvantages mentioned above.
=> Use `-` instead of `HEAD` in GitHub URLs

docs/api.md
There's a few places where we referred to "casks" as "formulae".
VSCode autoformatted the Markdown here, might want to view this without whitespace changes.
=> docs/api: fix cask naming.

_layouts/formula.html
Removing the `scope` attribute from `td` elements addresses the following HTML validation error:
> The "scope" attribute on the "td" element is obsolete. Use the "scope" attribute on a "th" element instead.
The parent `th` elements already use a `scope` attribute and this change appears to render the same when tested in current browsers.
=> Remove scope attribute from td elements

_layouts/analytics.html, _layouts/formula.html
A few items in the analytics contain the text for an `Options` object, like `adns #<Options:0x0000000102592c90>`. When used in related HTML templates, we end up with `<code>adns #<Options:0x0000000102592c90></code>`, which produces various validation errors because the `Options` text is being treated as an element:
> Element "options:0x0000000102592c90" not allowed as child of element "code" in this context.
> End tag "code" violates nesting rules.
This PR resolves the errors by escaping the formula name in templates, so the related HTML is `<code>adns #&lt;Options:0x0000000102592c90&gt;</code>` instead.
There may be a better way to address this when generating the related JSON data (e.g., `_data/analytics/build-error/365d.json`) but escaping this in the HTML templates may be a good idea …
=> Escape formula name in templates

.github/workflows/scheduled.yml
This PR adds a new job to the scheduled site update workflow. This job runs at the end of the deploy portion of the workflow (i.e. at the same time as the Algolia recrawl). It runs no matter what the outcome of the previous jobs were, and exists to report instances where the scheduled site deploy fails. If the deploy (or any previous step) fails, @BrewTestBot will open a new issue in this repository with a link to the most recent failed run. Subsequent failed runs will cause the issue body to be updated to link to the newest failed run, and will not cause a new issue to be opened. If an issue is open and a run succeeds, @BrewTestBot will leave a comment linking to the first successful run and then close the issue.
I've set up an example issue …
=> Report site deploy failures by opening an issue

.github/workflows/scheduled.yml
We should be able to manually trigger a re-deploy of the site. For example, if we're making an API change in Homebrew/brew, we may want to have two-step system where we merge an API changed, wait for it to be deployed to the site, and then update the formula/cask loader to handle it. Instead of needing to wait an hour for the update to happen, we should be able to trigger one immediately and not have to wait.
=> Allow manual runs of the `scheduled.yml` workflow

.github/workflows/scheduled.yml
Remove accidental trailing `&&`.
=> workflows/scheduled: fix syntax.

.github/workflows/scheduled.yml
These don't fail the build but still shows a red failure state.
=> workflows/scheduled: ignore Algolia failures even harder.

_layouts/cask.html, _layouts/formula.html
It's `tap_git_head` and not `tap_revision`.
Fixes https://github.com/Homebrew/formulae.brew.sh/issues/716
=> Fix formula/cask GitHub links

_layouts/cask.html
It's `c.tap_git_head` and not `f.tap_git_head`.
=> Fix cask GitHub links

.github/workflows/scheduled.yml
We can have more than one job per repo just don't want more than one per ref.
=> workflows/scheduled: allow more concurrency.

_config.yml, _layouts/cask.html, _layouts/cask_json.json, _layouts/formula.html, _layouts/formula_json.json
Fetching loop items from the config file data reduces the number of temporary arrays that Liquid needs to create and seems to speed up generation slightly; `241.446 seconds` vs. `230.459 seconds` in my testing.
=> layouts: define more data in _config.yml

script/generate.rb
This provides a mild speedup when we know nothing will change on disk.
=> script/generate.rb: enable factory cache.

.github/workflows/scheduled.yml
The job now takes ~8m so this gives us a bit of room while increasing the frequency of updates 4x.
=> scheduled: update every 15m.

.github/workflows/scheduled.yml, .gitignore, Rakefile, script/generate-cask.rb
This is going to be more reliable than querying homebrew-cask directly.
=> Re-add cask-source API.

.github/workflows/scheduled.yml, script/sign-json.rb, script/validate-build.rb
This uses JSON Web Signatures with a 4096-bit RSA key using RSA-PSS. The JSON structure is defined by RFC7515 (and RFC7797 for the `b64` part).
The endpoints are /api/formula.jws.json and /api/cask.jws.json.
Other endpoints are not signed at this time.
=> Add signed API endpoints

.github/workflows/scheduled.yml, .github/workflows/tests.yml, Gemfile, README.md, Rakefile
Remake of https://github.com/Homebrew/formulae.brew.sh/pull/786
Use the new `brew generate-analytics-api` command that will be added in https://github.com/Homebrew/homebrew-formula-analytics/pull/374 (this can't be merged until that is merged)
Also, while we're here, let's clean up the `Rakefile` and GitHub actions workflow a bit:
- Rename the `cask` task to `casks` for consistency
- Remove the option to generate analytics for only macOS/Linux
- Remove the option to generate analytics _and_ either core or cask data in the same task (this just didn't seem necessary)
- Add a new `generate` task that generates the entire site (`formulae`, `casks`, `analytics` and `api_samples`)
- Make the `generate` task the default task
- Remove some unused methods
- Use `/usr/bin/rake` across the board to …
=> Use `brew generate-analytics-api` and cleanup `Rakefile`

.github/workflows/scheduled.yml
This should let a crawl actually complete and rebuild the index.
=> CI: remove Algolia crawl start from scheduled run

Gemfile, Rakefile, _config.yml, _layouts/formula.html, analytics-linux/build-error/30d/index.html, analytics-linux/install-on-request/30d/index.html, analytics-linux/install/30d/index.html, analytics/build-error/30d/index.html, analytics/index.md, analytics/install-on-request/30d/index.html, analytics/install/30d/index.html, analytics/os-version/30d/index.html
- 30 day (InfluxDB) analytics data is shared on macOS and Linux
- Add `faraday-retry` gem so Jekyll stops complaining about it on startup
- Let `brew style --fix` do some reformatting
=> Fix analytics data

script/generate-api-samples.rb
Reverts Homebrew/formulae.brew.sh#852
Should fix sample generation now that the underlying JSON is back to original format.
=> Revert "generate-api-samples: fix generation"

.github/workflows/scheduled.yml, .gitignore, Rakefile, _config.yml, _layouts/analytics.html, _layouts/formula.html, _layouts/formula_json.json, analytics-linux/build-error/365d/index.html, analytics-linux/build-error/90d/index.html, analytics-linux/install-on-request/365d/index.html, analytics-linux/install-on-request/90d/index.html, analytics-linux/install/365d/index.html, analytics-linux/install/90d/index.html, analytics/build-error/365d/index.html, analytics/build-error/90d/index.html, analytics/index.md, analytics/install-on-request/365d/index.html, analytics/install-on-request/90d/index.html, analytics/install/365d/index.html, analytics/install/90d/index.html, analytics/os-version/365d/index.html, analytics/os-version/90d/index.html, docs/api.md
- separate analytics-linux is no longer generated
- display start date and total events on analytics pages
- redirect from analytics-linux pages
- update API documentation
While we're here
- display (disabled) or (deprecated) on formula pages
Fixes https://github.com/Homebrew/formulae.brew.sh/issues/856
Fixes https://github.com/Homebrew/brew/issues/15528
Fixes https://github.com/Homebrew/brew/issues/13211
=> Migrate all analytics to InfluxDB

Gemfile
Jekyll 4 is compatible with the GitHub Pages deployed from GitHub Actions pipeline we're using and generates about 3x faster on my machine.
=> Gemfile: use newer Jekyll.

.github/workflows/scheduled.yml, .github/workflows/tests.yml
`brew update-reset` does not exit with a failure code if the fetch fails, so a stale JSON could be generated in those scenarios (see https://github.com/Homebrew/brew/issues/15616). Replace the logic with https://github.com/Homebrew/actions/pull/382.
Also add some timeout values in case it prevents https://github.com/Homebrew/formulae.brew.sh/actions/runs/5322147907. Maybe not but no harm trying.
=> workflows/scheduled: remove cask update-reset

.github/workflows/scheduled.yml
Means less likely for failure if there's remote issues.
Requires https://github.com/Homebrew/actions/pull/391.
=> workflows/scheduled: skip core/cask updates where possible

.github/workflows/scheduled.yml, .github/workflows/tests.yml
Ensure that setup-homebrew is run with the correct options for each tap.
While we're here, set these everywhere and use the bundler cache.
Fixes https://github.com/Homebrew/formulae.brew.sh/issues/921
=> github/workflows: update taps.

.github/workflows/scheduled.yml
This may take some time to sort so unblock API generation for now by using the previous analytics data.
=> workflows/schduled: temporarily use previous analytics data

.github/workflows/scheduled.yml
This is the same token we're using elsewhere now.
=> workflows/scheduled: use new org token.

_layouts/cask.html, _layouts/formula.html
Instead of constructing the formula path manually, let's use `ruby_source_path` instead.
Fixes https://github.com/orgs/Homebrew/discussions/4704.
=> Support URL sharding

_config.yml
All the assets get copied by `remote_theme` anyway so we can just reference the copied image.
Fixes #955.
=> _config.yml: fix logo CSP violation

_layouts/cask.html
Follow-up to https://github.com/Homebrew/brew/pull/16292
Show a warning when casks are deprecated or disabled now.
---
Something interesting that I noticed (that affects both formulae and casks), the `title` attribute of the `h2` includes the deprecation reason, but it just uses the pre-set reason instead of converting it to the actual string.
For example, take `zdoom` (which will soon contain `deprecate! date: "2023-12-17", because: :discontinued`). Right now, the `title` attribute is set to:
```
This cask has been deprecated since 2023-12-17 because it discontinued
```
Instead of:
```
This cask has been deprecated since 2023-12-17 because it is discontinued upstream
```
Anyway, something for another PR
=> Add deprecated/disabled messages to cask pages

.github/workflows/scheduled.yml
Reverts Homebrew/formulae.brew.sh#985
Reverting until https://github.com/actions/download-artifact/issues/249 is resolved as it's made this job really flaky.
=> Revert "workflows/scheduled: use download/upload-artifact v4."

docs/api.md
`--all` is not a valid option for `brew info`
=> docs/api: drop non-functioning `--all`

.github/workflows/scheduled.yml, script/sign-json.rb
Now that the PR on the main brew repo got merged in we're generating the internal v3 JSON but we're not storing or using it anywhere. This updates the scheduled generation task to not only store the resulting JSON but also sign it to allow us to use it as a reference when building the loader code.
- https://github.com/Homebrew/brew/pull/16541
- https://github.com/Homebrew/brew/issues/16410
=> Start signing internal v3 json

script/generate-api-samples.rb
Make this less likely to fail.
Longer term, this probably shouldn't download anything and should just generate something locally.
=> script/generate-api-samples: add retries

_includes/cask.html
This PR updates the table layout on - https://formulae.brew.sh/cask/ To match the same layout as formulae - https://formulae.brew.sh/formula/
Related: https://github.com/Homebrew/brew/issues/16876
=> _includes/cask: update cask table layout

.github/workflows/scheduled.yml
I've spent too many hours on this and I ultimately think it's unfixable on our side. It's clear something very suddenly happened (like a server code deploy) for things to suddenly cease to function properly on larger datasets and may require reaching out to support. https://github.com/Homebrew/homebrew-formula-analytics/pull/433
So let's get this necromance this revert train before the previous data expires after 24 hours, and to restore API updates.
=> Revert "Revert "Revert "Revert "workflows/scheduled: temporarily use previous analytics data""""

.github/workflows/scheduled.yml, .github/workflows/tests.yml
Pin the version of the `setup-ruby` action to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
=> workflows: pin setup-ruby action

_includes/cask.html, cask_index.html
This changes the way we are handling the token. Currently, for casks including `@`, we see the following:
```html
<tr>
<td><a href="/cask/brave-browserbeta">brave-browserbeta</a></td>
<td>1.66.90.0</td>
<td>Web browser focusing on privacy</td>
<td>Brave Beta</td>
</tr>
``` 
instead of: 
```html
<tr>
<td><a href="/cask/brave-browser@beta">brave-browser@beta</a></td>
<td>1.66.90.0</td>
<td>Web browser focusing on privacy</td>
<td>Brave Beta</td>
</tr>
```
=> update cask token handling

_layouts/cask.html
As Liquid doesn't allow characters like `@`, `.`, or `+` in key names, we need to filter those out of cask token names as we did for formulae. More PRs are forthcoming, but this fixes the most obvious issue.
=> fix missing data in versioned cask pages

_includes/cask.html, _includes/casks.html, _layouts/cask.html, _layouts/cask_json.json, cask_index.html
This reworks how includes work for cask data (and fixes some missing conflicting cask links) by:
- rewording variables to distinguish between "token/tokens" (cask token strings), "data_token" (cask tokens adjusted to [match Jekyll's sanitization](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/readers/data_reader.rb#L70-L73)), "cask/casks" (full key+value info from site data), and "cdata" or "c" (cask value data whose properties can be fetched with dot notation),
- variables in includes have "include_" prepended to avoid lurking bugs with (lack of) variable scope
- changing `includes/casks.html` to infer a data_token from each of its passed tokens and pass those to `includes/cask.html`,
- changing `includes/cask.html` to expect a data_token and a token, and do its own cask data …
=> rework setup of cask includes

_includes/cask.html, _includes/formula.html, _includes/formulae.html, _layouts/cask.html, _layouts/formula.html, _layouts/formula_json.json, formula_index.html
These changes mirror those from #1153 for how formulae are handled, and also:
- changes `_layouts/cask.html` so that references to non-core casks in conflicts_with aren't skipped
- adds to `_includes/cask.html` the handling of references to old names of casks (depends on Homebrew/brew#17225)
- drops the number of characters to display of versions to 20
- removes a FUSE requirement reference
=> rework setup of formula includes

_config.yml, _includes/cask.html, _layouts/cask.html, _layouts/formula.html
This adds deprecated/disabled badges lists of casks, and copies over the deprecate/disable reasons from [`deprecate_disable.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/deprecate_disable.rb) and inserts either the full text [corresponding with the reason symbol](https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#deprecate-and-disable-reasons) into the hovertext or the text from the formula/cask itself if customized.
=> import & display full deprecate/disable reasons

_layouts/cask.html, _layouts/formula.html
Also fixes "odeprecated" being shown instead of old formula name.
=> show all former formula names / cask tokens

cask-font_index.html, index.html
Lists any cask fonts on https://formulae.brew.sh/cask-font/. Each font's page is still under /cask/; this just keeps the listing page lengths manageable.
=> list cask fonts on separate page

index.html
This breaks on my iPhone and it doesn't look that great.
=> index: don't allow breaking the line between "cask" and "fonts"

.github/workflows/docs.yml, .github/workflows/stale-issues.yml, .github/workflows/tests.yml
Pin the version of the actions to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
=> workflows: pin actions

.github/workflows/tests.yml
Python will become a dependency in https://github.com/Homebrew/homebrew-formula-analytics/pull/458.
CI in this PR here will fail until the other PR is merged, and once that other PR is merged then scheduled CI in this repo will start failing until this PR is merged.
=> workflows/tests: set up Python for new analytics handling

_layouts/analytics.html, analytics/brew-command-run-options/30d/index.html, analytics/brew-command-run-options/365d/index.html, analytics/brew-command-run-options/90d/index.html, analytics/brew-test-bot-test/30d/index.html, analytics/brew-test-bot-test/365d/index.html, analytics/brew-test-bot-test/90d/index.html, analytics/index.md
As-of https://github.com/Homebrew/homebrew-formula-analytics/pull/465 we now generate data for these events so let's add pages for them too.
=> Add more analytics pages for command options and test bot events

README.md
Functionality of `workflows/scheduled.yml` was moved into `workflows/tests.yml` in 7bce4cc0d5d7 Make workflows/scheduled replace workflows/tests. (2024-05-24).
=> Update workflow filename in README

.github/workflows/tests.yml
This was added in Homebrew/actions#588. It simplifies the workflow, and reduces the number of API calls.
=> workflows/tests: use `create-or-update-issue` action

.github/workflows/tests.yml
This allows us to save a few API calls for @BrewTestBot.
=> workflows/tests: use `github.token` to create issues

.github/workflows/tests.yml
Align CI setup with what has been done in https://github.com/Homebrew/brew/pull/18704
Use ubuntu-latest when the ubuntu version does not matter.
ubuntu-latest is equivalent to 22.04 right now so this does not change anything
=> ci: use ubuntu-latest

.github/workflows/tests.yml, script/sign-json.rb
This hasn't been used in a around 8 months since the approach didn't work as well as we initially hoped so we're removing it per https://github.com/Homebrew/brew/issues/19204#issuecomment-2636151650.
It should be safe to just remove this since it means that we're not archiving some generated files and not signing the files that are no longer being archived. In a follow-up PR, I'll remove the generation logic for the JSON files that no longer need to be updated from the main Brew repo.
This PR essentially reverts the following 2 commits:
- 439c237b18ff6e078e22d119b02f5ed73e59ec0b
- 8e4d93474ec9a711d9d6fb47c5255bc1519ab6ae
Related Links:
- New approach: https://github.com/Homebrew/brew/issues/19204
- Old approach: https://github.com/Homebrew/brew/issues/16410
CC: @Rylan12 since you might …
=> Revert JSON v3 logic

_includes/replacement.html, _layouts/cask.html, _layouts/formula.html
It would be nice to show what people can use instead of disabled/deprecated package.
Unfortunately I cannot test changes locally (`rake generate` throws `Error: No InfluxDB credentials found in HOMEBREW_INFLUXDB_TOKEN!`, `bundle install` needs different Ruby version: `Your Ruby version is 3.4.2, but your Gemfile specified 3.3.7`)
It would be nice to add styles to `<hr/>` tag
=> Idea: show recommended replacement

_layouts/formula.html
Now that the first ARM64 Linux bottles are available (e.g. https://formulae.brew.sh/formula/gnu-tar), split the bottle list into macOS on Apple Silicon, macOS on Intel, and Linux.
=> formula page: split Linux into its own section

_includes/attribute.html, _includes/replacement.html, _layouts/analytics.html, _layouts/cask.html, _layouts/formula.html
Adds displaying of future EOL dates if known. Fixes #1776. Examples: https://formulae.brew.sh/cask/mumble@snapshot, https://formulae.brew.sh/formula/go-boring
Also threw in some layout fixes & improvements I had on hand.
=> formula/cask pages: show future EOL dates

.github/workflows/tests.yml, script/sign-json.rb
See https://github.com/Homebrew/brew/pull/20038
Since these are meant to eventually replace the `{formula,cask}.jws.json` files, they should also be signed. Unless there's a reason not to, I figure we may as well set that up now.
This is marked as a draft until https://github.com/Homebrew/brew/pull/20038 is merged.
=> Sign `api/internal` API files

.github/workflows/tests.yml
See https://github.com/Homebrew/homebrew-command-not-found/issues/246
This PR pulls the latest `executables.txt` file to be served at `https://formulae.brew.sh/api/internal/executables.txt` for future use by `brew which-formula`.
Although as I'm opening this I'm wondering: is serving this from formulae.brew.sh better than having users download directly from GitHub?
=> Add `executables.txt` from `Homebrew/command-not-found` to internal API

.github/workflows/tests.yml
See https://github.com/Homebrew/formulae.brew.sh/issues/2000#issuecomment-3246601507
We don't want to cancel in-progress generation jobs for concurrency reasons. Instead, let the previous job finish and simply add the new job to a queue. This will reduce the frequency of generation failures if the generation job happens to take a long time.
Although it's worth noting, this will make it harder to catch issues that result in API generation taking an unusually long time.
=> Only cancel in-progress scheduled generation in pull requests

.github/workflows/tests.yml
`test-bot` has been merged into Homebrew/brew, so this is no longer necessary and outputs a warning in CI.
---
- https://github.com/Homebrew/brew/pull/20762
=> workflows: remove `test-bot` Action inputs
